import { escapeHtml, escapeHttpUrlAttribute, REFERENCE_SITE_URL } from "./html.js";

type LegalDocument = {
  description: string;
  path: string;
  title: string;
  markdown: string;
};

const legalDocuments: LegalDocument[] = [
  {
    path: "/legal/privacy",
    title: "Privacy Policy",
    description: "Privacy Policy for qURL",
    markdown: `# Privacy Policy for qURL

**Effective Date:** May 28, 2026

LayerV, Inc. ("we", "us", or "our") operates qURL, an MCP server that receives structured parameters generated by a large language model and processes them to provide access and routing functionality for authorized tools and services.

## 1. Information We Collect

We may collect the following information:

- Structured data generated by the AI model from user input
- Tool parameters and request metadata
- Logs necessary for operation, security, and troubleshooting
- Technical information such as IP address, timestamps, and error logs
- Any information you voluntarily provide through our services

We do not intentionally collect the full raw conversation history from ChatGPT unless it is included in the structured parameters sent to us.

## 2. How We Use Information

We use collected information to:

- Provide and operate qURL
- Process tool requests and return results
- Maintain security, prevent abuse, and debug issues
- Comply with legal obligations

## 3. Retention

We retain data only as long as necessary to provide the service or as required for legal, security, or operational purposes. Data is automatically cleared when it expires or when no longer needed.

## 4. Sharing of Information

We may share information with trusted service providers that help us operate the service, such as hosting, email, and infrastructure providers. We do not sell personal information.

## 5. Security

We use reasonable administrative, technical, and physical safeguards to protect information.

## 6. Your Rights

Depending on your location, you may have rights to access, correct, delete, or restrict certain personal information. To exercise these rights, contact us at the address below.

## 7. Children's Privacy

qURL is not intended for children under 13, and we do not knowingly collect personal information from them.

## 8. International Users

Your information may be processed in the United States and other locations where our service providers operate.

## 9. Changes to This Policy

We may update this Privacy Policy from time to time. The updated version will be posted on this page with a revised effective date.

## 10. Contact Us

If you have questions about this Privacy Policy, contact us at:
\`privacy@layerv.ai\`
`,
  },
  {
    path: "/legal/terms",
    title: "Terms of Service",
    description: "Terms of Service for qURL",
    markdown: `# Terms of Service for qURL

**Effective Date:** May 28, 2026

These Terms of Service ("Terms") govern your access to and use of qURL and related services provided by LayerV, Inc. ("LayerV", "we", "us", or "our"). By accessing or using qURL, you agree to these Terms.

## 1. Service

qURL is a service that helps route, protect, manage, or facilitate access to tools, files, services, APIs, applications, and related resources. qURL may receive structured parameters generated by large language models or connected systems in order to perform requested operations.

## 2. Eligibility

You may use qURL only if you are legally able to enter into a binding agreement under applicable law. If you use qURL on behalf of an organization, you represent that you have authority to bind that organization to these Terms.

## 3. Use of the Service

You may use qURL only in compliance with these Terms and applicable law. You agree not to:

- use qURL for unlawful, harmful, fraudulent, abusive, or deceptive activity;
- interfere with or disrupt the service, infrastructure, or security of qURL;
- attempt to gain unauthorized access to any system, account, token, or data;
- use qURL to transmit malware, spam, or other harmful code or content;
- misuse automated systems, rate limits, access tokens, or security controls;
- use qURL in a way that infringes the rights of LayerV or others.

## 4. Inputs and Processing

qURL may process structured inputs, tool parameters, metadata, and operational information necessary to provide the service. qURL is designed to receive processed or structured information from connected AI systems or tools and does not intentionally require the full raw text of user conversations unless such content is included in the request sent to us.

You are responsible for ensuring that you have the rights and permissions necessary to submit any data, content, or instructions to the service.

## 5. Accounts and Access

Some features may require an account, credentials, API keys, tokens, or third-party platform access. You are responsible for maintaining the confidentiality of your credentials and for activities that occur under your access.

You must notify us promptly if you believe your account, token, or credentials have been compromised.

## 6. Acceptable Security Use

You may not bypass, disable, probe, or reverse engineer access controls or security protections except as expressly authorized by law or by us in writing.

## 7. Intellectual Property

LayerV and its licensors retain all rights, title, and interest in and to qURL, including all software, branding, content, and related intellectual property, except for content or data you lawfully provide.

Subject to these Terms, we grant you a limited, non-exclusive, non-transferable, revocable right to use the service.

## 8. Feedback

If you provide feedback, suggestions, or ideas regarding qURL, you grant us a non-exclusive, worldwide, royalty-free right to use them for any lawful purpose without obligation to you.

## 9. Privacy

Your use of qURL is also subject to our Privacy Policy. To the extent qURL processes personal information, we handle it in accordance with the Privacy Policy and applicable law.

## 10. Third-Party Services

qURL may interoperate with third-party services, platforms, models, hosting providers, or communication tools. We are not responsible for third-party services or their acts, omissions, content, availability, or policies.

## 11. Service Availability and Changes

We may modify, suspend, or discontinue any part of qURL at any time, with or without notice, to the extent permitted by law. We may also update these Terms from time to time by posting the revised version.

## 12. Termination

We may suspend or terminate your access if we believe you violated these Terms, created risk for the service or others, or if suspension is necessary for security, legal, or operational reasons. You may stop using the service at any time.

Sections that by their nature should survive termination will survive, including sections relating to intellectual property, disclaimers, limitation of liability, and governing law.

## 13. Disclaimers

qURL is provided on an "as is" and "as available" basis. To the maximum extent permitted by law, LayerV disclaims all warranties, express or implied, including warranties of merchantability, fitness for a particular purpose, non-infringement, and uninterrupted or error-free operation.

We do not guarantee that the service will always be secure, available, accurate, or suitable for every use case.

## 14. Limitation of Liability

To the maximum extent permitted by law, LayerV and its affiliates, officers, employees, agents, suppliers, and licensors will not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, or for any loss of profits, revenues, data, goodwill, or business opportunities arising out of or related to your use of qURL.

To the maximum extent permitted by law, LayerV's total liability for any claim arising out of or relating to the service or these Terms will not exceed the amount you paid us, if any, for the service giving rise to the claim during the twelve months before the event giving rise to liability.

## 15. Indemnification

You agree to defend, indemnify, and hold harmless LayerV and its affiliates, officers, employees, and agents from and against claims, liabilities, damages, losses, and expenses arising out of or related to your misuse of qURL, your violation of these Terms, or your violation of any law or third-party rights.

## 16. Governing Law

These Terms are governed by the laws of the State of Delaware, without regard to conflict of law principles, except to the extent otherwise required by applicable law.

## 17. Contact

If you have questions about these Terms, contact us at:
\`info@layerv.ai\`

or

\`privacy@layerv.ai\`
`,
  },
];

function renderInlineMarkdown(value: string): string {
  // Escape source text before adding trusted formatting tags. Reversing this
  // order would allow source HTML to survive the markdown replacements.
  const escaped = escapeHtml(value);
  return escaped
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
}

export function renderMarkdownToHtml(markdown: string): string {
  const lines = markdown.replace(/\r\n/g, "\n").split("\n");
  const html: string[] = [];
  let paragraph: string[] = [];
  let listItems: string[] = [];

  const flushParagraph = () => {
    if (paragraph.length === 0) return;
    html.push(`<p>${renderInlineMarkdown(paragraph.join(" "))}</p>`);
    paragraph = [];
  };

  const flushList = () => {
    if (listItems.length === 0) return;
    html.push("<ul>");
    for (const item of listItems) {
      html.push(`<li>${renderInlineMarkdown(item)}</li>`);
    }
    html.push("</ul>");
    listItems = [];
  };

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) {
      flushParagraph();
      flushList();
      continue;
    }

    const headingMatch = /^(#{1,3})\s+(.+)$/.exec(line);
    if (headingMatch) {
      flushParagraph();
      flushList();
      const level = Math.min(headingMatch[1].length, 3);
      html.push(`<h${level}>${renderInlineMarkdown(headingMatch[2])}</h${level}>`);
      continue;
    }

    const bulletMatch = /^-\s+(.+)$/.exec(line);
    if (bulletMatch) {
      flushParagraph();
      listItems.push(bulletMatch[1]);
      continue;
    }

    if (line === "or") {
      flushParagraph();
      flushList();
      html.push(`<p class="legal-or">${renderInlineMarkdown(line)}</p>`);
      continue;
    }

    paragraph.push(line);
  }

  flushParagraph();
  flushList();
  return html.join("\n");
}

function renderLegalShell(document: LegalDocument, baseUrl: string): string {
  const canonicalUrl = new URL(document.path, baseUrl).toString();
  const body = renderMarkdownToHtml(document.markdown);

  // `body` is trusted HTML only because renderMarkdownToHtml escapes every
  // source text node before adding its small, fixed tag vocabulary. Keep that
  // invariant if legal copy ever becomes request- or operator-supplied.
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(document.description)} | LayerV</title>
    <meta name="description" content="${escapeHtml(document.description)}" />
    <link rel="canonical" href="${escapeHttpUrlAttribute(canonicalUrl)}" />
    <style>
      :root {
        color-scheme: dark;
        --bg: #0a0d09;
        --panel: rgba(20, 24, 18, 0.88);
        --panel-strong: rgba(14, 18, 12, 0.96);
        --border: rgba(194, 255, 66, 0.14);
        --text: #f5f7f1;
        --muted: #b8c0b2;
        --accent: #b9ff2c;
        --accent-soft: rgba(185, 255, 44, 0.12);
        --shadow: 0 24px 80px rgba(0, 0, 0, 0.45);
      }

      * {
        box-sizing: border-box;
      }

      body {
        margin: 0;
        min-height: 100vh;
        font-family: "Segoe UI", "Helvetica Neue", Helvetica, Arial, sans-serif;
        color: var(--text);
        background:
          linear-gradient(rgba(255,255,255,0.04) 1px, transparent 1px),
          linear-gradient(90deg, rgba(255,255,255,0.04) 1px, transparent 1px),
          radial-gradient(circle at top left, rgba(185,255,44,0.12), transparent 24%),
          linear-gradient(180deg, #0d100c 0%, #070906 100%);
        background-size: 48px 48px, 48px 48px, auto, auto;
      }

      a {
        color: var(--accent);
        text-decoration: none;
      }

      a:hover {
        text-decoration: underline;
      }

      .shell {
        width: min(1180px, calc(100% - 32px));
        margin: 0 auto;
      }

      .topbar {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 16px;
        padding: 22px 0 18px;
      }

      .brand {
        display: inline-flex;
        align-items: center;
        gap: 12px;
        color: var(--text);
        font-size: 0.96rem;
        letter-spacing: 0.04em;
      }

      .brand-mark {
        width: 40px;
        height: 2px;
        border-radius: 999px;
        background: linear-gradient(90deg, transparent, var(--accent));
        box-shadow: 0 0 18px rgba(185, 255, 44, 0.5);
      }

      .home-link {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        min-height: 48px;
        padding: 0 18px;
        border-radius: 14px;
        background: var(--accent);
        color: #11140d;
        font-weight: 700;
        box-shadow: 0 14px 40px rgba(185, 255, 44, 0.24);
      }

      .hero {
        padding: 36px 0 24px;
      }

      .eyebrow {
        margin: 0 0 16px;
        color: var(--accent);
        font-size: 0.92rem;
        font-weight: 700;
        letter-spacing: 0.18em;
        text-transform: uppercase;
      }

      .hero-grid {
        display: grid;
        grid-template-columns: minmax(0, 1.3fr) minmax(280px, 0.9fr);
        gap: 28px;
        align-items: start;
      }

      .hero h1 {
        margin: 0;
        font-size: clamp(2.8rem, 6vw, 5.25rem);
        line-height: 0.95;
        font-weight: 300;
        letter-spacing: -0.04em;
        max-width: 8ch;
      }

      .hero-copy {
        margin-top: 20px;
        max-width: 640px;
        color: var(--muted);
        font-size: 1.08rem;
        line-height: 1.8;
      }

      .summary-card {
        padding: 22px 22px 20px;
        border: 1px solid var(--border);
        border-radius: 24px;
        background: var(--panel);
        box-shadow: var(--shadow);
      }

      .summary-card h2 {
        margin: 0 0 14px;
        font-size: 1rem;
        color: var(--accent);
      }

      .summary-card p {
        margin: 0;
        color: var(--muted);
        line-height: 1.75;
      }

      .document-card {
        margin: 22px 0 72px;
        padding: 28px;
        border-radius: 28px;
        border: 1px solid var(--border);
        background: linear-gradient(180deg, var(--panel) 0%, var(--panel-strong) 100%);
        box-shadow: var(--shadow);
      }

      .document-toolbar {
        display: flex;
        align-items: center;
        gap: 10px;
        margin-bottom: 22px;
        padding-bottom: 16px;
        border-bottom: 1px solid rgba(255,255,255,0.08);
      }

      .dot {
        width: 10px;
        height: 10px;
        border-radius: 999px;
      }

      .dot.red { background: #ff5f57; }
      .dot.yellow { background: #febc2e; }
      .dot.green { background: #28c840; }

      .doc-label {
        margin-left: 8px;
        color: var(--muted);
        font-size: 0.92rem;
        letter-spacing: 0.08em;
        text-transform: lowercase;
      }

      .legal-content {
        max-width: 860px;
      }

      .legal-content h1,
      .legal-content h2,
      .legal-content h3 {
        margin: 0;
        scroll-margin-top: 24px;
      }

      .legal-content h1 {
        font-size: clamp(2rem, 4vw, 2.8rem);
        line-height: 1.08;
        margin-bottom: 18px;
      }

      .legal-content h2 {
        margin-top: 30px;
        margin-bottom: 12px;
        font-size: 1.28rem;
        color: var(--accent);
      }

      .legal-content h3 {
        margin-top: 22px;
        margin-bottom: 10px;
        font-size: 1.06rem;
      }

      .legal-content p,
      .legal-content li {
        color: var(--muted);
        font-size: 1rem;
        line-height: 1.85;
      }

      .legal-content p {
        margin: 0 0 14px;
      }

      .legal-content ul {
        margin: 0 0 16px;
        padding-left: 22px;
      }

      .legal-content code {
        padding: 0.18rem 0.45rem;
        border-radius: 999px;
        background: var(--accent-soft);
        color: var(--text);
        font-family: "Consolas", "SFMono-Regular", monospace;
        font-size: 0.95em;
      }

      .legal-content strong {
        color: var(--text);
      }

      .legal-or {
        color: var(--accent);
        font-size: 0.92rem;
        text-transform: uppercase;
        letter-spacing: 0.18em;
      }

      .footer {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 16px;
        padding: 0 0 36px;
        color: var(--muted);
        font-size: 0.95rem;
      }

      @media (max-width: 860px) {
        .shell {
          width: min(100% - 24px, 100%);
        }

        .topbar,
        .footer,
        .hero-grid {
          grid-template-columns: 1fr;
          flex-direction: column;
          align-items: flex-start;
        }

        .document-card {
          padding: 20px;
          border-radius: 22px;
        }

        .home-link {
          width: 100%;
        }
      }
    </style>
  </head>
  <body>
    <div class="shell">
      <header class="topbar">
        <a class="brand" href="${escapeHttpUrlAttribute(REFERENCE_SITE_URL)}" aria-label="LayerV Home">
          <span class="brand-mark" aria-hidden="true"></span>
          <span>LayerV Legal</span>
        </a>
        <a class="home-link" href="${escapeHttpUrlAttribute(REFERENCE_SITE_URL)}">Back to layerv.ai</a>
      </header>

      <section class="hero">
        <p class="eyebrow">Public Legal Document</p>
        <div class="hero-grid">
          <div>
            <h1>${escapeHtml(document.title)}</h1>
            <p class="hero-copy">
              This public statement page is served by the qURL service and styled to align with the LayerV website's visual language for consistency.
            </p>
          </div>
          <aside class="summary-card">
            <h2>${escapeHtml(document.description)}</h2>
            <p>
              LayerV public legal page for external review, compliance submission, and direct sharing.
            </p>
          </aside>
        </div>
      </section>

      <article class="document-card">
        <div class="document-toolbar" aria-hidden="true">
          <span class="dot red"></span>
          <span class="dot yellow"></span>
          <span class="dot green"></span>
          <span class="doc-label">${escapeHtml(document.path)}</span>
        </div>
        <div class="legal-content">
          ${body}
        </div>
      </article>

      <footer class="footer">
        <span>LayerV legal pages</span>
        <a href="${escapeHttpUrlAttribute(REFERENCE_SITE_URL)}">${escapeHtml(REFERENCE_SITE_URL)}</a>
      </footer>
    </div>
  </body>
</html>`;
}

export function getLegalDocuments(): LegalDocument[] {
  return legalDocuments.map((document) => ({ ...document }));
}

export function findLegalDocument(pathname: string): LegalDocument | undefined {
  return legalDocuments.find((document) => document.path === pathname);
}

export function renderLegalDocumentHtml(pathname: string, baseUrl: string): string | undefined {
  const document = findLegalDocument(pathname);
  if (!document) return undefined;
  return renderLegalShell(document, baseUrl);
}
